
#ifndef NL_KEY_H_
#define NL_KEY_H_

#if defined(_WIN32) || defined(PLATFORM_WINDOWS)
// Okay
#elif defined(__EMSCRIPTEN__) || defined(PLATFORM_WEB)
# include <emscripten/key_codes.h> // To use the DOM_PK codes
#else
# error Incomplete Platform Keys
#endif

enum class MouseButton : unsigned char
{
    Left = 0,
    Middle,
    Right
};

enum class ButtonState : unsigned char
{
    Up = 0, 
    Down = 1,
    Repeat,
};

// Make this an unsigned char or short?
enum class Key
{
#if defined(_WIN32)

    A = 'A', B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,
    ZERO = '0', ONE = '1', TWO = '2', THREE = '3', FOUR, FIVE, SIX, SEVEN, EIGHT, NINE,

#elif defined(__EMSCRIPTEN__)

    UNKOWN = DOM_PK_UNKNOWN,
    ESCAPE = DOM_PK_ESCAPE,
    ZERO = DOM_PK_0,
    ONE = DOM_PK_1,
    TWO = DOM_PK_2,
    THREE = DOM_PK_3,
    FOUR = DOM_PK_4,
    FIVE = DOM_PK_5,
    SIX = DOM_PK_6,
    SEVEN = DOM_PK_7,
    EIGHT = DOM_PK_8,
    NINE = DOM_PK_9,
    MINUS = DOM_PK_MINUS,
    EQUAL = DOM_PK_EQUAL,
    BACKSPACE = DOM_PK_BACKSPACE,
    TAB = DOM_PK_TAB,
    Q = DOM_PK_Q,
    W = DOM_PK_W,
    E = DOM_PK_E,
    R = DOM_PK_R,
    T = DOM_PK_T,
    Y = DOM_PK_Y,
    U = DOM_PK_U,
    I = DOM_PK_I,
    O = DOM_PK_O,
    P = DOM_PK_P,
    BRACKET_LEFT = DOM_PK_BRACKET_LEFT,
    BRACKET_RIGHT = DOM_PK_BRACKET_RIGHT,
    ENTER = DOM_PK_ENTER,
    CONTROL_LEFT = DOM_PK_CONTROL_LEFT,
    A = DOM_PK_A,
    S = DOM_PK_S,
    D = DOM_PK_D,
    F = DOM_PK_F,
    G = DOM_PK_G,
    H = DOM_PK_H,
    J = DOM_PK_J,
    K = DOM_PK_K,
    L = DOM_PK_L,
    SEMICOLON = DOM_PK_SEMICOLON,
    QUOTE = DOM_PK_QUOTE,
    BACKQUOTE = DOM_PK_BACKQUOTE,
    SHIFT_LEFT = DOM_PK_SHIFT_LEFT,
    BACKSLASH = DOM_PK_BACKSLASH,
    Z = DOM_PK_Z,
    X = DOM_PK_X,
    C = DOM_PK_C,
    V = DOM_PK_V,
    B = DOM_PK_B,
    N = DOM_PK_N,
    M = DOM_PK_M,
    COMMA = DOM_PK_COMMA,
    PERIOD = DOM_PK_PERIOD,
    SLASH = DOM_PK_SLASH,
    SHIFT_RIGHT = DOM_PK_SHIFT_RIGHT,
    NUMPAD_MULTIPLY = DOM_PK_NUMPAD_MULTIPLY,
    ALT_LEFT = DOM_PK_ALT_LEFT,
    SPACE = DOM_PK_SPACE,
    CAPS_LOCK = DOM_PK_CAPS_LOCK,
    F1 = DOM_PK_F1,
    F2 = DOM_PK_F2,
    F3 = DOM_PK_F3,
    F4 = DOM_PK_F4,
    F5 = DOM_PK_F5,
    F6 = DOM_PK_F6,
    F7 = DOM_PK_F7,
    F8 = DOM_PK_F8,
    F9 = DOM_PK_F9,
    F10 = DOM_PK_F10,
    PAUSE = DOM_PK_PAUSE,
    SCROLL_LOCK = DOM_PK_SCROLL_LOCK,
    NUMPAD_7 = DOM_PK_NUMPAD_7,
    NUMPAD_8 = DOM_PK_NUMPAD_8,
    NUMPAD_9 = DOM_PK_NUMPAD_9,
    NUMPAD_SUBTRACT = DOM_PK_NUMPAD_SUBTRACT,
    NUMPAD_4 = DOM_PK_NUMPAD_4,
    NUMPAD_5 = DOM_PK_NUMPAD_5,
    NUMPAD_6 = DOM_PK_NUMPAD_6,
    NUMPAD_ADD = DOM_PK_NUMPAD_ADD,
    NUMPAD_1 = DOM_PK_NUMPAD_1,
    NUMPAD_2 = DOM_PK_NUMPAD_2,
    NUMPAD_3 = DOM_PK_NUMPAD_3,
    NUMPAD_0 = DOM_PK_NUMPAD_0,
    NUMPAD_DECIMAL = DOM_PK_NUMPAD_DECIMAL,
    PRINT_SCREEN = DOM_PK_PRINT_SCREEN,
    INTL_BACKSLASH = DOM_PK_INTL_BACKSLASH,
    F11 = DOM_PK_F11,
    F12 = DOM_PK_F12,
    NUMPAD_EQUAL = DOM_PK_NUMPAD_EQUAL,
    F13 = DOM_PK_F13,
    F14 = DOM_PK_F14,
    F15 = DOM_PK_F15,
    F16 = DOM_PK_F16,
    F17 = DOM_PK_F17,
    F18 = DOM_PK_F18,
    F19 = DOM_PK_F19,
    F20 = DOM_PK_F20,
    F21 = DOM_PK_F21,
    F22 = DOM_PK_F22,
    F23 = DOM_PK_F23,
    KANA_MODE = DOM_PK_KANA_MODE,
    LANG_2 = DOM_PK_LANG_2,
    LANG_1 = DOM_PK_LANG_1,
    INTL_RO = DOM_PK_INTL_RO,
    F24 = DOM_PK_F24,
    CONVERT = DOM_PK_CONVERT,
    NON_CONVERT = DOM_PK_NON_CONVERT,
    INTL_YEN = DOM_PK_INTL_YEN,
    NUMPAD_COMMA = DOM_PK_NUMPAD_COMMA,
    PASTE = DOM_PK_PASTE,
    MEDIA_TRACK_PREVIOUS = DOM_PK_MEDIA_TRACK_PREVIOUS,
    CUT = DOM_PK_CUT,
    COPY = DOM_PK_COPY,
    MEDIA_TRACK_NEXT = DOM_PK_MEDIA_TRACK_NEXT,
    NUMPAD_ENTER = DOM_PK_NUMPAD_ENTER,
    CONTROL_RIGHT = DOM_PK_CONTROL_RIGHT,
    AUDIO_VOLUME_MUTE = DOM_PK_AUDIO_VOLUME_MUTE,
    LAUNCH_APP_2 = DOM_PK_LAUNCH_APP_2,
    MEDIA_PLAY_PAUSE = DOM_PK_MEDIA_PLAY_PAUSE,
    MEDIA_STOP = DOM_PK_MEDIA_STOP,
    EJECT = DOM_PK_EJECT,
    AUDIO_VOLUME_DOWN = DOM_PK_AUDIO_VOLUME_DOWN,
    AUDIO_VOLUME_UP = DOM_PK_AUDIO_VOLUME_UP,
    BROWSER_HOME = DOM_PK_BROWSER_HOME,
    NUMPAD_DIVIDE = DOM_PK_NUMPAD_DIVIDE,
    ALT_RIGHT = DOM_PK_ALT_RIGHT,
    HELP = DOM_PK_HELP,
    NUM_LOCK = DOM_PK_NUM_LOCK,
    HOME = DOM_PK_HOME,
    UP_ARROW = DOM_PK_ARROW_UP,
    PAGE_UP = DOM_PK_PAGE_UP,
    LEFT_ARROW = DOM_PK_ARROW_LEFT,
    RIGHT_ARROW = DOM_PK_ARROW_RIGHT,
    END = DOM_PK_END,
    DOWN_ARROW = DOM_PK_ARROW_DOWN,
    PAGE_DOWN = DOM_PK_PAGE_DOWN,
    INSERT = DOM_PK_INSERT,
    DELETE = DOM_PK_DELETE,
    META_LEFT = DOM_PK_META_LEFT,
    OS_LEFT = DOM_PK_OS_LEFT,
    META_RIGHT = DOM_PK_META_RIGHT,
    OS_RIGHT = DOM_PK_OS_RIGHT,
    CONTEXT_MENU = DOM_PK_CONTEXT_MENU,
    POWER = DOM_PK_POWER,
    BROWSER_SEARCH = DOM_PK_BROWSER_SEARCH,
    BROWSER_FAVORITES = DOM_PK_BROWSER_FAVORITES,
    BROWSER_REFRESH = DOM_PK_BROWSER_REFRESH,
    BROWSER_STOP = DOM_PK_BROWSER_STOP,
    BROWSER_FORWARD = DOM_PK_BROWSER_FORWARD,
    BROWSER_BACK = DOM_PK_BROWSER_BACK,
    LAUNCH_APP_1 = DOM_PK_LAUNCH_APP_1,
    LAUNCH_MAIL = DOM_PK_LAUNCH_MAIL,
    LAUNCH_MEDIA_PLAYER = DOM_PK_LAUNCH_MEDIA_PLAYER,
    MEDIA_SELECT = DOM_PK_MEDIA_SELECT


#elif

# error Incomplete Platform Keys Implementation

#endif
};

#endif //NL_KEY_H_